function [frame, nosex,nosey,nosel,RightForex,RightForey,RightForel,LeftForex,LeftForey,LeftForel,RightHindToex,RightHindToey,RightHindToel,RightHindMidx, RightHindMidy, RightHindMidl, RightHindHeelx,RightHindHeely,RightHindHeell,LeftHindToex,LeftHindToey,LeftHindToel,LeftHindMidx, LeftHindMidy, LeftHindMidl, LeftHindHeelx,LeftHindHeely,LeftHindHeell,MirrorRightHindx,MirrorRightHindy,MirrorRightHindl,MirrorLeftHindx,MirrorLeftHindy,MirrorLeftHindl,Backx,Backy,Backl,TailBasex,TailBasey,TailBasel,ABforcePlateCenterx,ABforcePlateCentery,ABforcePlateCenterl,CDforcePlateCenterx,CDforcePlateCentery,CDforcePlateCenterl] = sciimport(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [SCORER,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_180000,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_1,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_2,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_3,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_4,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_5,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_6,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_7,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_8,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_9,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_10,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_11,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_12,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_13,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_14,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_15,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_16,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_17,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_18,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_19,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_20,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_21,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_22,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_23,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_24,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_25,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_26]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [SCORER,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_180000,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_1,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_2,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_3,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_4,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_5,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_6,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_7,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_8,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_9,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_10,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_11,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_12,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_13,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_14,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_15,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_16,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_17,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_18,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_19,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_20,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_21,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_22,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_23,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_24,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_25,DLC_RESNET50_SCIATICAMAR25SHUFFLE1_26]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [scorer,DLC_resnet50_SciaticaMar25shuffle1_180000,DLC_resnet50_SciaticaMar25shuffle1_1,DLC_resnet50_SciaticaMar25shuffle1_2,DLC_resnet50_SciaticaMar25shuffle1_3,DLC_resnet50_SciaticaMar25shuffle1_4,DLC_resnet50_SciaticaMar25shuffle1_5,DLC_resnet50_SciaticaMar25shuffle1_6,DLC_resnet50_SciaticaMar25shuffle1_7,DLC_resnet50_SciaticaMar25shuffle1_8,DLC_resnet50_SciaticaMar25shuffle1_9,DLC_resnet50_SciaticaMar25shuffle1_10,DLC_resnet50_SciaticaMar25shuffle1_11,DLC_resnet50_SciaticaMar25shuffle1_12,DLC_resnet50_SciaticaMar25shuffle1_13,DLC_resnet50_SciaticaMar25shuffle1_14,DLC_resnet50_SciaticaMar25shuffle1_15,DLC_resnet50_SciaticaMar25shuffle1_16,DLC_resnet50_SciaticaMar25shuffle1_17,DLC_resnet50_SciaticaMar25shuffle1_18,DLC_resnet50_SciaticaMar25shuffle1_19,DLC_resnet50_SciaticaMar25shuffle1_20,DLC_resnet50_SciaticaMar25shuffle1_21,DLC_resnet50_SciaticaMar25shuffle1_22,DLC_resnet50_SciaticaMar25shuffle1_23,DLC_resnet50_SciaticaMar25shuffle1_24,DLC_resnet50_SciaticaMar25shuffle1_25,DLC_resnet50_SciaticaMar25shuffle1_26] = importfile('Sciatica_01152019_R05_on_T09DLC_resnet50_SciaticaMar25shuffle1_180000filtered.csv',4, 1205);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/04/06 16:04:57

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 4;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
frame = dataArray{:, 1};

nosex = dataArray{:, 2};
nosey = dataArray{:, 3};
nosel = dataArray{:, 4};

RightForex = dataArray{:, 5};
RightForey = dataArray{:, 6};
RightForel = dataArray{:, 7};
LeftForex = dataArray{:, 8};
LeftForey = dataArray{:, 9};
LeftForel = dataArray{:, 10};

RightHindToex = dataArray{:, 11};
RightHindToey = dataArray{:, 12};
RightHindToel = dataArray{:, 13};
    RightHindMidx = dataArray{:, 14};
    RightHindMidy = dataArray{:, 15};
    RightHindMidl = dataArray{:, 16};
        RightHindHeelx = dataArray{:, 17};
        RightHindHeely = dataArray{:, 18};
        RightHindHeell = dataArray{:, 19};
LeftHindToex = dataArray{:, 20};
LeftHindToey = dataArray{:, 21};
LeftHindToel = dataArray{:, 22};
    LeftHindMidx = dataArray{:, 23};
    LeftHindMidy = dataArray{:, 24};
    LeftHindMidl = dataArray{:, 25};
        LeftHindHeelx = dataArray{:, 26};
        LeftHindHeely = dataArray{:, 27};
        LeftHindHeell = dataArray{:, 28};

MirrorRightHindx =	dataArray{:, 29};
MirrorRightHindy =	dataArray{:, 30};
MirrorRightHindl =  dataArray{:, 31};
MirrorLeftHindx	= dataArray{:, 32};
MirrorLeftHindy	= dataArray{:, 33};
MirrorLeftHindl = dataArray{:, 34};

Backx = dataArray{:, 35};
Backy = dataArray{:, 36};
Backl = dataArray{:, 37};

TailBasex = dataArray{:, 38};
TailBasey = dataArray{:, 39};
TailBasel = dataArray{:, 40};

ABforcePlateCenterx = dataArray{:, 41};
ABforcePlateCentery = dataArray{:, 42};
ABforcePlateCenterl = dataArray{:, 43};
    CDforcePlateCenterx = dataArray{:, 44};
    CDforcePlateCentery = dataArray{:, 45};
    CDforcePlateCenterl = dataArray{:, 46};


end